version: '3.3'
networks:
  app-network:
    driver: bridge
services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - '3306:3306'
    volumes:
      - './others/db/scripts/quickmenu.sql:/docker-entrypoint-initdb.d/init.sql'
      - dbdata:/var/lib/mysql
    networks:
      - app-network
volumes:
  dbdata: